import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const literataItalic = localFont({
  src: '../fonts/Literata/Literata-Italic-VariableFont.ttf',
  variable: '--font-ibarra-italic',
  display: 'swap',
})

const literataRegular = localFont({
  src: '../fonts/Literata/Literata-VariableFont.ttf',
  variable: '--font-ibarra-regular',
  display: 'swap',
})

const fustat = localFont({
  src: [
    { path: '../fonts/fustat/Fustat-ExtraLight.ttf', weight: '200' },
    { path: '../fonts/fustat/Fustat-Light.ttf', weight: '300' },
    { path: '../fonts/fustat/Fustat-Regular.ttf', weight: '400' },
    { path: '../fonts/fustat/Fustat-Medium.ttf',  weight: '500' },
    { path: '../fonts/fustat/Fustat-SemiBold.ttf',  weight: '600' },
    { path: '../fonts/fustat/Fustat-Bold.ttf',    weight: '700' },
    { path: '../fonts/fustat/Fustat-ExtraBold.ttf',    weight: '800' },
  ],
  variable: '--font-fustat',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Paisa Rupay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${literataItalic.variable} ${literataRegular.variable} ${fustat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
