import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/src/common/Header/header";

const literataItalic = localFont({
  src: '../fonts/Literata/Literata-Italic-VariableFont.ttf',
  variable: '--font-literata-italic',
  display: 'swap',
})

const literataRegular = localFont({
  src: '../fonts/Literata/Literata-VariableFont.ttf',
  variable: '--font-literata-regular',
  display: 'swap',
})

const fustat = localFont({
  src: [
    { path: '../fonts/Fustat/static/Fustat-ExtraLight.ttf', weight: '200' },
    { path: '../fonts/Fustat/static/Fustat-Light.ttf', weight: '300' },
    { path: '../fonts/Fustat/static/Fustat-Regular.ttf', weight: '400' },
    { path: '../fonts/Fustat/static/Fustat-Medium.ttf',  weight: '500' },
    { path: '../fonts/Fustat/static/Fustat-SemiBold.ttf',  weight: '600' },
    { path: '../fonts/Fustat/static/Fustat-Bold.ttf',    weight: '700' },
    { path: '../fonts/Fustat/static/Fustat-ExtraBold.ttf',    weight: '800' },
  ],
  variable: '--font-fustat',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Paisa Rupay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${literataItalic.variable} ${literataRegular.variable} ${fustat.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/dist/tabler-icons.min.css"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
